########################################################################
########################################################################
##
##  Docker Compose File: SABnzbd (LinuxServer.io)
##  Function: Usenet Download Client
##
##  Documentation: https://docs.linuxserver.io/images/docker-sabnzbd
##
########################################################################
########################################################################
version: "3.7"

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/sabnzbd:/config
      - ${FOLDER_FOR_USENET:?err}:/data/usenet
      - ${FOLDER_FOR_WATCH:?err}:/data/watch
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sabnzbd
      - TP_THEME=${TP_THEME:?err}

# Configure VPN / Direct Internet access below. You will also need to make change in the Gluetun VPN Container

    network_mode: "container:gluetun"                        ## Disable to bypass Gluetun VPN for Internet traffic
#    ports:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#      - "${WEBUI_PORT_SABNZBD:?err}:8080"                   ## Enable  to bypass Gluetun VPN for Internet traffic
#networks:                                                   ## Enable  to bypass Gluetun VPN for Internet traffic
#  default:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#    name: media_network                                     ## Enable  to bypass Gluetun VPN for Internet traffic
#    external: true                                          ## Enable  to bypass Gluetun VPN for Internet traffic
