###########################################################################
###########################################################################
##
##    Docker Compose File: Heimdall (LinuxServer.io)
##    Function: Organise links to web sites and web applications
##
##    Documentation: https://docs.linuxserver.io/images/docker-heimdall
##    https://docs.linuxserver.io/general/swag#using-heimdall-as-the-home-page-at-domain-root
##
###########################################################################
###########################################################################
version: "3.7"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/heimdall:/config
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}

# NOTE: Heimdall MUST NOT connect to the Gluetun VPN container

networks:
  default:
    name: media-network
    external: true
