###########################################################################
###########################################################################
##
##  Docker Compose File: Whisparr (Hotio.Dev)
##  Function: Adult Media Library Manager
##
##  Documentation: https://wiki.servarr.com/whisparr
##
###########################################################################
###########################################################################
version: "3.7"

services:
  whisparr:
    image: hotio/whisparr:nightly
    container_name: whisparr
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/whisparr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
    network_mode: "container:gluetun"

# Ports are disabled in containers when they are connected to VPN, as the
# Gluetun container manages the ports for containers that connect via VPN

#    ports:
#      - "${WEBUI_PORT_WHISPARR:?err}:6969"             # Configured in Gluetun VPN container
