###########################################################################
###########################################################################
##
##  Docker Compose File: Mylar3 (LinuxServer.io)
##  Function: Comic Library Manager
##
##  Documentation: https://github.com/mylar3/mylar3/wiki
##
###########################################################################
###########################################################################
version: "3.7"

services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/mylar3:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:mylar3
      - TP_THEME=${TP_THEME:?err}
    network_mode: "container:gluetun"

# Ports are disabled in containers when they are connected to VPN, as the
# Gluetun container manages the ports for containers that connect via VPN

#    ports:
#      - "${WEBUI_PORT_MYLAR3:?err}:8090"             # Configured in Gluetun VPN container
